### ISSUE TITLE
Advanced options mention of "auto complete"

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/documentation#181]
### URL to the relevant documentation

https://github.com/Qiskit/documentation/pull/180

### Select all that apply

- [ ] typo
- [ ] code bug
- [ ] out-of-date content
- [ ] broken link
- [X] other

### Describe the fix.

Is this referring to type hints resulting in your IDE having auto-complete? It's a weird thing to say in docs. Better would be to link to the API reference.

Not everyone has auto-complete also, such as using Vim (without all the fancy extensions).

**Comment by abbycross** [comment]
I believe this has been addressed - @Eric-Arellano ok to close?

**Comment by Eric-Arellano** [comment]
It still shows up:

```
docs/run/advanced-runtime-options.mdx
28:The `Options` class supports auto-complete. Once you create an instance of the `Options` class, you can use auto-complete to see what options are available. If you choose one of the categories, you can use auto-complete again to see what options are available under that category. 
```

It looks like it comes from the API docs. I'm not sure what it refers to? Note that there may be no problem! This only looked fishy to me.

```
❯ rg 'auto-complete' -l
translations/ja/run/advanced-runtime-options.mdx
scripts/lib/api/processHtml.test.ts
docs/api/qiskit-ibm-runtime/0.14/options.md
docs/api/qiskit-ibm-runtime/options.md
docs/api/qiskit-ibm-runtime/0.16/options.md
docs/api/qiskit-ibm-runtime/0.15/options.md
docs/run/advanced-runtime-options.mdx
docs/api/qiskit/release-notes/0.28.md
```

**Comment by abbycross** [comment]
Ah sorry, I totally misread the issue -- @beckykd or @jyu00 any thoughts on whether this is a problem?

**Comment by javabster** [comment]
@Eric-Arellano apparently Jessie is keen to emphasise the autocomplete aspect, so closing this issue
